name: Run tests for PR

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        release: ["latest", "rawhide"]

    steps:
    - uses: actions/checkout@v1
    - name: Run Fedora tests
      run: tests/run-fedora ${{ matrix.release }}
